New log file opened at Sun Feb 21 11:11:33 JST 2016 by 1031@StefanOnAir.local
Taking next connection to: 49571
New client attempting to connect on port: 49572-49571
  Address = /192.168.129.35:49571
This client on port 49572 has uuid 4b0a8e54-3aac-4787-9bbd-f412df26b770 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-4b0a8e54-3aac-4787-9bbd-f412df26b770
Taking next connection to: 49571
New client attempting to connect on port: 49573-49571
  Address = /192.168.129.35:49571
Handshake exception on socket: 49573
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49571
New client attempting to connect on port: 49574-49571
  Address = /192.168.129.35:49571
This client on port 49574 has uuid a39b33e0-b6a7-46a9-9029-1abbde91a70c configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-4b0a8e54-3aac-4787-9bbd-f412df26b770, activator-a39b33e0-b6a7-46a9-9029-1abbde91a70c
Taking next connection to: 49571
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49571
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49571
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49571
New client attempting to connect on port: 49759-49571
  Address = /192.168.129.35:49571
Handshake exception on socket: 49759
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49571
New client attempting to connect on port: 49760-49571
  Address = /192.168.129.35:49571
This client on port 49760 has uuid b4250461-4753-41a4-bbd5-25146ae7aa06 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-a39b33e0-b6a7-46a9-9029-1abbde91a70c, play-fork-run-b4250461-4753-41a4-bbd5-25146ae7aa06
Taking next connection to: 49571
